FROM python:3.7 
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY config.py.example config.py

CMD [ "gunicorn", "-c", "gunicorn.conf.py", "--bind", "0.0.0.0:5000", "wsgi" ]
