name: Staging

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  testdocker:
    name: Test docker-compose stack
    runs-on: ubuntu-18.04
    timeout-minutes: 5
   
    steps:
    - name: Update apt-get
      run: |
        sudo apt-get update
    # Build compose stack - "staging environment"
    - uses: actions/checkout@v2 

    - name: Build user backend image
      run: docker build -t test_user-backend -f Dockerfile-prod .

    - name: Build complete stack
      run: docker-compose -f docker-compose.staging.yml up -d

    - name: Check containers are running
      run: |
        docker ps -a
        [ $(docker ps -a | awk -F '[[:space:]][[:space:]]+' 'FNR > 1 { print $5 }' | grep -c "Up") -eq 2 ]

    - name: Confirm flask is running
      run: curl -s --retry 10 --retry-connrefused http://localhost:5000/

    # Run functional black box tests of API
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-comptests-${{ hashFiles('comptests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-comptests-

    - name: Install dependencies
      run: pip install -r comptests/requirements.txt

    - name: Run functional tests using pytest and requests
      run: pytest comptests